global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rag-api-java'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rag-api:8080']

  - job_name: 'embedding-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['embedding-service:8001']

  - job_name: 'ingestion-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ingestion-service:8000']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
